import { useEffect, useState } from 'react'
import './App.css'
import { authService } from './services/authService'

const currentPath = () => window.location.pathname.replace(/\/$/, '') || '/login'

export default function App() {
  const [path, setPath] = useState(currentPath())
  const [user, setUser] = useState(null)
  const [loading, setLoading] = useState(true)
  const navigate = (next) => { window.history.pushState({}, '', next); setPath(next) }
  useEffect(() => { const pop = () => setPath(currentPath()); window.addEventListener('popstate', pop); return () => window.removeEventListener('popstate', pop) }, [])
  useEffect(() => { if (!authService.getToken()) return setLoading(false); authService.me().then(setUser).catch(() => authService.clearToken()).finally(() => setLoading(false)) }, [])
  const authenticated = (nextUser, token) => { authService.saveSession(token, nextUser); setUser(nextUser); navigate('/dashboard') }
  const logout = async () => { await authService.logout(); setUser(null); navigate('/login') }
  if (loading) return <div className="loading-screen">Loading your workspace…</div>
  if (path === '/dashboard') return user ? <Dashboard user={user} onLogout={logout} /> : <Redirect navigate={navigate} />
  if (user && (path === '/login' || path === '/signup')) return <Redirect navigate={navigate} />
  return path === '/signup' ? <Signup navigate={navigate} onAuthenticated={authenticated} /> : <Login navigate={navigate} onAuthenticated={authenticated} />
}

function Redirect({ navigate }) { useEffect(() => navigate('/login'), [navigate]); return <div className="loading-screen">Redirecting…</div> }
function Shell({ children, signup, navigate }) { return <main className="auth-layout"><section className="brand-panel"><div className="brand-mark">✓</div><p className="brand-name">TodoFlow</p><h1>Make space for<br /><em>what matters.</em></h1><p className="brand-copy">A calmer way to organize your day, one task at a time.</p><div className="brand-decoration"><span /><span /><span /></div></section><section className="form-panel"><div className="form-wrap"><p className="eyebrow">{signup ? 'Get started' : 'Welcome back'}</p><h2>{signup ? 'Create your account' : 'Log in to TodoFlow'}</h2><p className="form-subtitle">{signup ? 'A little more focus, a lot less friction.' : 'Pick up right where you left off.'}</p>{children}<p className="switch-copy">{signup ? 'Already have an account?' : "Don't have an account?"} <button className="text-button" onClick={() => navigate(signup ? '/login' : '/signup')}>{signup ? 'Log in' : 'Sign up'}</button></p></div></section></main> }
function Field({ label, type = 'text', value, onChange, placeholder, autoComplete }) { return <label className="field"><span>{label}</span><input type={type} value={value} onChange={onChange} placeholder={placeholder} autoComplete={autoComplete} /></label> }

function Login({ navigate, onAuthenticated }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async e => { e.preventDefault(); setError(''); setBusy(true); try { const result = await authService.login({ email, password }); onAuthenticated(result.user, result.token) } catch (err) { setError(err.message) } finally { setBusy(false) } }; return <Shell navigate={navigate}><form onSubmit={submit} className="auth-form">{error && <div className="alert">{error}</div>}<Field label="Email address" type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email" /><Field label="Password" type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter your password" autoComplete="current-password" /><button className="primary-button" disabled={busy}>{busy ? 'Logging in…' : 'Log in'} <span>→</span></button></form></Shell> }
function Signup({ navigate }) { const [form, setForm] = useState({ name: '', email: '', password: '', confirmPassword: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const update = key => e => setForm({ ...form, [key]: e.target.value }); const submit = async e => { e.preventDefault(); setError(''); if (form.password !== form.confirmPassword) return setError('Passwords do not match.'); setBusy(true); try { await authService.signup(form); navigate('/login') } catch (err) { setError(err.message) } finally { setBusy(false) } }; return <Shell signup navigate={navigate}><form onSubmit={submit} className="auth-form">{error && <div className="alert">{error}</div>}<Field label="Full name" value={form.name} onChange={update('name')} placeholder="Alex Morgan" autoComplete="name" /><Field label="Email address" type="email" value={form.email} onChange={update('email')} placeholder="you@example.com" autoComplete="email" /><Field label="Password" type="password" value={form.password} onChange={update('password')} placeholder="At least 8 characters" autoComplete="new-password" /><Field label="Confirm password" type="password" value={form.confirmPassword} onChange={update('confirmPassword')} placeholder="Repeat your password" autoComplete="new-password" /><button className="primary-button" disabled={busy}>{busy ? 'Creating account…' : 'Create account'} <span>→</span></button></form></Shell> }

function Dashboard({ user, onLogout }) { return <main className="dashboard"><header className="topbar"><div className="logo"><span>✓</span> TodoFlow</div><button className="logout-button" onClick={onLogout}>Log out</button></header><section className="dashboard-content"><p className="eyebrow">Your workspace</p><h1>Welcome, {user.name.split(' ')[0]}.</h1><p className="dashboard-lede">Everything you need to keep your day moving with intention.</p><div className="empty-card"><div className="empty-icon">✦</div><h2>Your main module is ready</h2><p>This is your space for tasks, projects, and the things that matter most. Your productivity tools will live here.</p><span className="coming-soon">Coming soon</span></div><div className="user-card"><div className="avatar">{user.name.charAt(0).toUpperCase()}</div><div><p className="card-label">Signed in as</p><strong>{user.name}</strong><p>{user.email}</p></div></div></section></main> }
